name: mkdocs-generation 
on:
  push:
    branches:
      - develop
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: python3 -m pip install mkdocs-material[imaging],mkdocs-material-extensions,mkdocstrings[python],pillow,cairosvg

      - run: mkdocs gh-deploy --force
